[tool.poetry]
name = "notebooks"
version = "0.1.0"
description = ""
authors = ["\"truonghm\" <\"truong173@outlook.com\">"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.10"
pandas = "^2.2.1"
numpy = "^1.26.4"
scikit-learn = "^1.4.1.post1"
matplotlib = "^3.8.3"
networkx = "^3.2.1"
seaborn = "^0.13.2"
torch = {version = "^2.2.1+cpu", source = "pytorch-cpu"}
ipykernel = "^6.29.3"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu117"
priority = "explicit"


[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
